
host = 192.168.100.66
port = 24800
name = omarchy 
#width = 1024
#height = 768
xkb_key_offset = 8

[screensaver]
start = pkill -SIGUSR1 swayidle
#stop = pkill swaylock


xkb_keymap {
        xkb_keycodes  { include "aliases(qwerty)"     };
        xkb_types     { include "complete"    };
        xkb_compat    { include "complete"    };
        xkb_symbols   { include "pc+us+inet(evdev)"     };
        xkb_geometry  { include "pc(pc105)"   };
};

[raw-keymap]
347 = 125  # super key
331 = 105  # esquerda
336 = 108  # baixo
328 = 103  # cima
333 = 106  # direita
